### ISSUE TITLE
discussion

### ISSUE THREAD

**Issue by kittenvr** [VargurStorm/MauveWolf#1]
could you please open discussion up so i can ask how to change sideberry accent color

**Comment by VargurStorm** [comment]
I've opened up discussions now. To directly answer your question, though, it will depend exactly which accent colour you're referring to.

For the tab highlights, you can update CSS that points to the border shadow within Sidebery.
If you need to change the button accent from light blue to something else, you can do it in here: https://color.firefox.com/ (Check out the Advanced Colors > Button Background Hover)

**Comment by kittenvr** [comment]
> I've opened up discussions now. To directly answer your question, though, it will depend exactly which accent colour you're referring to.
> 
> For the tab highlights, you can update CSS that points to the border shadow within Sidebery. If you need to change the button accent from light blue to something else, you can do it in here: https://color.firefox.com/ (Check out the Advanced Colors > Button Background Hover)

what is the border shadow within Sidebery called in the css?
i would like to change it to #ffae00.

**Comment by VargurStorm** [comment]
**The border is handled by:**

`#root.root {--tabs-activated-shadow: 0 1px 4px -1px rgba(0,0,0,0.282), inset 0 0 0 1px rgb(165, 92, 251), inset 4px 0 0 0 #f388ffff;}`

**The Activated text colour being pink is handled by:**
`#root.root {--tabs-activated-fg: #f388ffff;}`

---

The formed of these two is split into two borders so you'll want to update that line like so:
![SCR-20240122-bgsz](https://github.com/VargurStorm/MauveWolf/assets/40493346/1691cfe2-6b88-4098-a85f-3fc79d892789)

```css
#root.root {--tabs-activated-shadow: 0 1px 4px -1px rgba(0,0,0,0.282), inset 0 0 0 1px #2596BE, inset 4px 0 0 0 #2596BE;}
```

I do hope to make this more maintainable. Honestly didn't expect people to like it :D

**Comment by kittenvr** [comment]
Change #root.root {--tabs-activated-fg: #f388ffff;} to
#root.root {--tabs-activated-fg: #ffae00;}?

**Comment by kittenvr** [comment]
>This is what it will look like for you by the way (if you just change the border)
How do I also change the colored text?

**Comment by VargurStorm** [comment]
The --tabs-activated-fg that you mentioned is responsible for the text. I mentioned this in my reply before. Reiterated below for complete clarity. You are just changing the hex codes here referencing colours.

**Replace this (Activated border):**
`#root.root {--tabs-activated-shadow: 0 1px 4px -1px rgba(0,0,0,0.282), inset 0 0 0 1px rgb(165, 92, 251), inset 4px 0 0 0 #f388ffff;}`

**With this:**
```css
#root.root {--tabs-activated-shadow: 0 1px 4px -1px rgba(0,0,0,0.282), inset 0 0 0 1px #2596BE, inset 4px 0 0 0 #2596BE;}
```
--- 

**And replace this (activated text colour):**
`#root.root {--tabs-activated-fg: #f388ffff;}`

**With this:**
```css
#root.root {--tabs-activated-fg: #2596BE;}
```
